---
- hosts: all
  remote_user: cbtmadmin
  tasks:
    - name: Get source for IRIS Core
      git: repo='https://github.com/suttonpd/iris_core.git'
           dest=~/iris_core
    - name: Get source for IRIS Modules
      git: repo='https://github.com/suttonpd/iris_modules.git'
           dest=~/iris_modules
    - name: Install basic utilities (C++ compiler)
      apt: name=build-essential
      become: true
    - name: Install BOOST
      apt: name=libboost-all-dev update_cache=yes
      become: true
    - name: Install FFTw
      apt: name=libfftw3-dev update_cache=yes
      become: true
    - name: Install CMake
      apt: name=cmake update_cache=yes
      become: true
    - name: Install Protobuf
      apt: name=libprotobuf-dev update_cache=yes
      become: true
    - name: Install Protobuf compiler
      apt: name=protobuf-compiler
      become: true
    - name: Install Package Config
      apt: name=pkgconf
      become: true
    - name: Create build directory for IRIS core
      file: path=~/iris_core/build state=directory
    - name: cmake IRIS core
      command: cmake -DDISABLE_QT=ON ../ 
      args:
        chdir: ~/iris_core/build
    - name: make IRIS core
      command: make
      args:
        chdir: ~/iris_core/build
    - name: Install IRIS core
      command: make install
      become: true
      args:
        chdir: /home/cbtmadmin/iris_core/build
    - name: Create build directory for IRIS Modules
      file: path=~/iris_modules/build state=directory
    - name: Disable RfFrontEnd Controler
      lineinfile: dest=~/iris_modules/controllers/CMakeLists.txt 
        line='ADD_SUBDIRECTORY(RfFrontEnd)' 
        state=absent
    - name: cmake IRIS Modules
      command: cmake ../
      args:
        chdir: ~/iris_modules/build
    - name: make IRIS Modules
      command: make
      args:
        chdir: ~/iris_modules/build
    - name: Install IRIS Modules
      command: make install
      become: true
      args:
        chdir: /home/cbtmadmin/iris_modules/build
    - name: Do ldconfig
      command: ldconfig
      become: true
